version: '3.8'

services:
  postgres:
    image: 'postgres'
    container_name: 'jwt_postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db/data:/var/lib/postgresql/jwt_postgres
networks:
  sme_default:
    external: true
